CREATE TABLE users
(
    id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
    username VARCHAR(32) NOT NULL,
    email VARCHAR(320) NOT NULL,
    password VARCHAR(255) NOT NULL,
    about VARCHAR(4000) NULL,
    last_online DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    joined_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);